import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// Font files can be colocated inside of `pages`
const kanakira = localFont({
  src: './images/fonts/Kanakira/Kanakira-BoldInktrap.woff2',
  variable: '--font-Kanakira-BoldInktrap'
});
const kanakiraItalic = localFont({
  src: './images/fonts/Kanakira/Kanakira-BoldInktrapItalic.woff2',
  variable: '--font-Kanakira-BoldInktrapItalic'
});
const kanakiraHeavy = localFont({
  src: './images/fonts/Kanakira/Kanakira-HeavyInktrap.woff2',
  variable: '--font-Kanakira-HeavyInktrap'
});
const kanakiraHeavyItalic = localFont({
  src: './images/fonts/Kanakira/Kanakira-HeavyInktrapItalic.woff2',
  variable: '--font-Kanakira-HeavyInktrapItalic'
});
const mabryBold = localFont({
  src: './images/fonts/Mabry/MabryPro-Bold.ttf',
  variable: '--font-MabryPro-Bold'
});
const mabryBoldItalic = localFont({
  src: './images/fonts/Mabry/MabryPro-BoldItalic.ttf',
  variable: '--font-MabryPro-BoldItalic'
});
const mabryItalic = localFont({
  src: './images/fonts/Mabry/MabryPro-Italic.ttf',
  variable: '--font-MabryPro-Italic'
});
const mabryLight = localFont({
  src: './images/fonts/Mabry/MabryPro-Light.ttf',
  variable: '--font-MabryPro-Light'
});
const mabryLightItalic = localFont({
  src: './images/fonts/Mabry/MabryPro-LightItalic.ttf',
  variable: '--font-MabryPro-LightItalic'
});
const mabryRegular = localFont({
  src: './images/fonts/Mabry/MabryPro-Regular.ttf',
  variable: '--font-MabryPro-Regular'
});

interface LayoutProps {
  children: React.ReactNode;
  metaDefault: Metadata; // Assuming Metadata is the correct type for metaDefault
}

export default function RootLayout({
  children,
  metaDefault, // Add metaDefault to the props
}: LayoutProps) {
  return (
    <html lang="en">

      <body className={`

      ${mabryRegular.className} 
      ${kanakira.className}
      ${kanakiraItalic.className}
      ${kanakiraHeavy.className}
      ${kanakiraHeavyItalic.className}
      ${mabryBold.className}
      ${mabryBoldItalic.className}
      ${mabryItalic.className}
      ${mabryLight.className}
      ${mabryLightItalic.className}
      ${mabryLightItalic.className}
      `} >
        {children}
      </body>
    </html>
  );
}
